# SPDX-FileCopyrightText: 2025 mohamed hamdi <haamdi@outlook.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync

    - name: Build binaries
      run: |
        # Get version from tag
        VERSION=${GITHUB_REF#refs/tags/}

        # Create dist directory
        mkdir -p dist

        # Build for x86_64
        uv run pyinstaller --onefile main.py --log-level=FATAL --name audconv-linux-amd64

    - name: Create checksums
      run: |
        cd dist
        sha256sum audconv-* > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/audconv-linux-amd64
          dist/checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
